<template>
	<view class="cart-page">
		<view class="page-head"><view><text class="kicker">SHOPPING BAG</text><text class="title">购物车</text></view><text v-if="items.length" class="count">{{ items.length }} 件商品</text></view>
		<StateView v-if="!loggedIn" title="登录后查看购物车" description="你的商品会安全保存在账号中" action-text="去登录" @action="goLogin" />
		<view v-else-if="loading" class="loading">正在加载购物车...</view>
		<StateView v-else-if="!items.length" title="购物车还是空的" description="去挑选一些喜欢的商品吧" action-text="去逛逛" @action="goShopping" />
		<view v-else class="cart-list">
			<view v-for="item in items" :key="item.id" class="cart-item">
				<view class="check" :class="{checked:item.selected}" @tap="toggleItem(item)">{{ item.selected?'✓':'' }}</view>
				<image class="item-image" :src="item.image||'/static/logo.png'" mode="aspectFill" @tap="openProduct(item)" />
				<view class="item-copy"><text class="item-name" @tap="openProduct(item)">{{ item.name }}</text><text v-if="item.skuName" class="sku-name">{{ item.skuName }}</text><view class="item-bottom"><text class="price">¥{{ formatPrice(item.price) }}</text><view class="stepper"><button @tap="changeQuantity(item,-1)">−</button><text>{{ item.quantity }}</text><button @tap="changeQuantity(item,1)">+</button></view></view><text class="delete" @tap="removeItem(item)">删除</text></view>
			</view>
		</view>
		<view v-if="loggedIn&&items.length" class="checkout-bar"><view class="select-all" @tap="toggleAll"><view class="check" :class="{checked:allSelected}">{{ allSelected?'✓':'' }}</view><text>全选</text></view><view class="total"><text>合计</text><text>¥{{ formatPrice(totalPrice) }}</text></view><button :disabled="!selectedItems.length" @tap="checkout">结算 ({{ selectedCount }})</button></view>
	</view>
</template>

<script>
	import StateView from '../../components/StateView.vue'
	import {deleteCartItem,getCart,selectAllCart,setCartSelected,updateCartQuantity} from '../../api/index.js'
	import {formatMoney} from '../../utils/format.js'
	import {normalizeCartList} from '../../utils/normalizers.js'
	import {isLoggedIn} from '../../utils/auth.js'
	export default{
		components:{StateView},data(){return{loggedIn:false,loading:false,items:[],updating:new Set()}},
		computed:{selectedItems(){return this.items.filter((item)=>item.selected)},allSelected(){return this.items.length>0&&this.selectedItems.length===this.items.length},selectedCount(){return this.selectedItems.reduce((sum,item)=>sum+item.quantity,0)},totalPrice(){return this.selectedItems.reduce((sum,item)=>sum+item.price*item.quantity,0)}},
		onShow(){this.loggedIn=isLoggedIn();if(this.loggedIn)this.loadCart();else this.items=[]},
		onPullDownRefresh(){this.loadCart(true)},
		methods:{formatPrice:formatMoney,async loadCart(fromPull=false){this.loading=!fromPull;try{this.items=normalizeCartList(await getCart())}catch(error){uni.showToast({title:error.message,icon:'none'})}finally{this.loading=false;uni.stopPullDownRefresh()}},async toggleItem(item){if(this.updating.has(item.id))return;const next=!item.selected;item.selected=next;this.updating.add(item.id);try{await setCartSelected(item.id,next?1:0)}catch(error){item.selected=!next;uni.showToast({title:error.message,icon:'none'})}finally{this.updating.delete(item.id)}},async toggleAll(){const next=!this.allSelected;const previous=this.items.map((item)=>item.selected);this.items.forEach((item)=>item.selected=next);try{await selectAllCart(next?1:0)}catch(error){this.items.forEach((item,index)=>item.selected=previous[index]);uni.showToast({title:error.message,icon:'none'})}},async changeQuantity(item,step){if(this.updating.has(item.id))return;const next=Math.max(1,Math.min(99,item.quantity+step));if(next===item.quantity)return;const previous=item.quantity;item.quantity=next;this.updating.add(item.id);try{await updateCartQuantity(item.id,next)}catch(error){item.quantity=previous;uni.showToast({title:error.message,icon:'none'})}finally{this.updating.delete(item.id)}},removeItem(item){uni.showModal({title:'移出购物车',content:'确定删除这件商品吗？',confirmColor:'#e1251b',success:async(result)=>{if(!result.confirm)return;try{await deleteCartItem(item.id);this.items=this.items.filter((entry)=>entry.id!==item.id);uni.showToast({title:'已删除',icon:'success'})}catch(error){uni.showToast({title:error.message,icon:'none'})}}})},checkout(){const ids=this.selectedItems.map((item)=>item.id).join(',');uni.navigateTo({url:`/pages/checkout/index?cartIds=${ids}`})},openProduct(item){if(item.productId)uni.navigateTo({url:`/pages/products/detail?id=${item.productId}`})},goShopping(){uni.switchTab({url:'/pages/index/index'})},goLogin(){uni.navigateTo({url:'/pages/auth/login?redirect=%2Fpages%2Fcart%2Findex'})}},
	}
</script>

<style scoped>
	.cart-page{min-height:100vh;padding-bottom:150rpx;background:#f5f6f8}.page-head{display:flex;padding:calc(var(--status-bar-height) + 34rpx) 28rpx 26rpx;align-items:flex-end;justify-content:space-between;background:#fff}.kicker,.title{display:block}.kicker{color:#e1251b;font-size:18rpx;font-weight:800}.title{margin-top:7rpx;color:#22272e;font-size:40rpx;font-weight:800}.count{color:#949ba5;font-size:22rpx}.cart-list{padding:18rpx 22rpx}.cart-item{display:flex;margin-bottom:16rpx;padding:24rpx 20rpx;align-items:center;border:1rpx solid #eceef1;border-radius:12rpx;background:#fff}.check{display:flex;width:38rpx;height:38rpx;flex:0 0 38rpx;align-items:center;justify-content:center;border:2rpx solid #cfd3d8;border-radius:50%;color:#fff;font-size:22rpx}.check.checked{border-color:#e1251b;background:#e1251b}.item-image{width:166rpx;height:166rpx;margin-left:18rpx;flex:0 0 166rpx;border-radius:8rpx;background:#f1f2f4}.item-copy{min-width:0;flex:1;margin-left:20rpx}.item-name{display:-webkit-box;overflow:hidden;color:#333940;font-size:26rpx;line-height:36rpx;-webkit-box-orient:vertical;-webkit-line-clamp:2}.sku-name{display:block;margin-top:9rpx;overflow:hidden;color:#9299a3;font-size:21rpx;text-overflow:ellipsis;white-space:nowrap}.item-bottom{display:flex;margin-top:18rpx;align-items:center;justify-content:space-between}.price{color:#e1251b;font-size:29rpx;font-weight:800}.stepper{display:flex;height:48rpx;align-items:center;border:1rpx solid #dfe2e6}.stepper button{width:48rpx;height:46rpx;margin:0;padding:0;border:0;border-radius:0;background:#f6f7f8;font-size:25rpx;line-height:46rpx}.stepper button::after{border:0}.stepper text{width:58rpx;text-align:center;font-size:22rpx}.delete{display:block;margin-top:12rpx;color:#a1a7af;font-size:20rpx;text-align:right}.checkout-bar{position:fixed;right:0;bottom:0;left:0;z-index:10;display:flex;min-height:104rpx;padding:0 18rpx env(safe-area-inset-bottom);align-items:center;border-top:1rpx solid #e2e4e7;background:#fff}.select-all{display:flex;align-items:center;gap:10rpx;color:#555d67;font-size:23rpx}.total{min-width:0;flex:1;margin:0 18rpx;text-align:right}.total text{color:#666e78;font-size:22rpx}.total text:last-child{display:block;color:#e1251b;font-size:31rpx;font-weight:800}.checkout-bar button{width:220rpx;height:76rpx;margin:0;border:0;border-radius:9rpx;color:#fff;background:#e1251b;font-size:25rpx;line-height:76rpx}.checkout-bar button::after{border:0}.checkout-bar button[disabled]{color:#fff;background:#c9ccd1}.loading{display:flex;height:60vh;align-items:center;justify-content:center;color:#969da6;font-size:24rpx}
</style>
