import request from '../utils/request.js'

export const getProducts = (query) => request({ url: '/products', query, auth: false })
export const getProductDetail = (id) => request({ url: `/products/${id}`, auth: false })
export const getProductReviews = (id, query) => request({ url: `/products/${id}/reviews`, query, auth: false })
export const getCategoryTree = () => request({ url: '/categories/tree', auth: false })
export const getCategoryChildren = (parentId) => request({ url: '/categories/children', query: { parentId }, auth: false })
export const getBrands = () => request({ url: '/brands', auth: false })
export const getBrandDetail = (id) => request({ url: `/brands/${id}`, auth: false })

export const login = (data) => request({ url: '/auth/login', method: 'POST', data, auth: false })
export const sendCode = (data) => request({ url: '/auth/send-code', method: 'POST', data, auth: false })
export const register = (data) => request({ url: '/auth/register', method: 'POST', data, auth: false })
export const getMockCode = (phone) => request({ url: '/auth/mock-code', query: { phone }, auth: false })
export const getUserInfo = () => request({ url: '/user/info' })
export const updateUserInfo = (data) => request({ url: '/user/info', method: 'PUT', data })
export const logout = () => request({ url: '/user/logout', method: 'POST' })

export const getCart = () => request({ url: '/cart' })
export const addToCart = (data) => request({ url: '/cart', method: 'POST', data })
export const setCartSelected = (id, selected) => request({ url: `/cart/${id}/selected`, method: 'PUT', query: { selected } })
export const updateCartQuantity = (id, quantity) => request({ url: `/cart/${id}/quantity`, method: 'PUT', query: { quantity } })
export const selectAllCart = (selected) => request({ url: '/cart/select-all', method: 'PUT', query: { selected } })
export const deleteCartItem = (id) => request({ url: `/cart/${id}`, method: 'DELETE' })

export const getFavorites = () => request({ url: '/favorites' })
export const checkFavorite = (productId) => request({ url: `/favorites/check/${productId}` })
export const addFavorite = (productId) => request({ url: `/favorites/${productId}`, method: 'POST' })
export const removeFavorite = (productId) => request({ url: `/favorites/${productId}`, method: 'DELETE' })

export const getOrders = (query) => request({ url: '/orders', query })
export const getOrderDetail = (orderNo) => request({ url: `/orders/${orderNo}` })
export const createOrder = (data) => request({ url: '/orders', method: 'POST', data })
export const buyNowOrder = (data) => request({ url: '/orders/buy-now', method: 'POST', data })
export const createReview = (data) => request({ url: '/orders/review', method: 'POST', data })
export const cancelOrder = (orderNo) => request({ url: `/orders/${orderNo}/cancel`, method: 'PUT' })
export const receiveOrder = (orderNo) => request({ url: `/orders/${orderNo}/receive`, method: 'PUT' })
export const deleteOrder = (orderNo) => request({ url: `/orders/${orderNo}`, method: 'DELETE' })

export const createPayment = (orderNo, payType) => request({ url: '/pay/create', method: 'POST', query: { orderNo, payType } })
export const confirmPayment = (paymentNo) => request({ url: '/pay/confirm', method: 'POST', query: { paymentNo } })
export const getPaymentStatus = (orderNo) => request({ url: '/pay/status', query: { orderNo } })

export const claimCoupon = (templateId) => request({ url: `/coupons/claim/${templateId}`, method: 'POST' })
export const getMyCoupons = (query) => request({ url: '/coupons/mine', query })
export const getAvailableCoupons = (query) => request({ url: '/coupons/available', query })

export const getAddressList = () => request({ url: '/address/list' })
export const getAddressDetail = (id) => request({ url: `/address/${id}` })
export const addAddress = (data) => request({ url: '/address', method: 'POST', data })
export const updateAddress = (data) => request({ url: '/address', method: 'PUT', data })
export const deleteAddress = (id) => request({ url: `/address/${id}`, method: 'DELETE' })
export const setDefaultAddress = (id) => request({ url: `/address/default/${id}`, method: 'PUT' })
