<template>
	<view class="coupon-page">
		<view class="page-head"><view><text class="kicker">MEMBER BENEFITS</text><text class="title">优惠券中心</text></view><text>{{ activeTab==='available'?'先领券，再购物':'管理已领取的优惠券' }}</text></view>
		<view class="main-tabs"><view :class="{active:activeTab==='available'}" @tap="changeTab('available')">领券中心</view><view :class="{active:activeTab==='mine'}" @tap="changeTab('mine')">我的优惠券</view></view>
		<scroll-view v-if="activeTab==='mine'" class="status-tabs" scroll-x><view class="status-inner"><view v-for="item in statuses" :key="item.value" :class="{active:status===item.value}" @tap="changeStatus(item.value)">{{ item.label }}</view></view></scroll-view>
		<view v-if="loading" class="loading">正在加载优惠券...</view>
		<StateView v-else-if="error" title="优惠券加载失败" :description="error" action-text="重新加载" error @action="loadCoupons" />
		<view v-else-if="visibleCoupons.length" class="coupon-list">
			<view v-for="coupon in visibleCoupons" :key="coupon.id" class="coupon-ticket" :class="{disabled:activeTab==='mine'&&coupon.status!==0}">
				<view class="coupon-value"><text>{{ valueText(coupon) }}</text><text>{{ coupon.minAmount>0?`满 ${amountText(coupon.minAmount)} 元可用`:'无门槛使用' }}</text></view>
				<view class="coupon-copy"><view><text>{{ coupon.shopName }}</text><text v-if="activeTab==='mine'" :class="`status-${coupon.status}`">{{ coupon.statusText }}</text></view><text class="coupon-name">{{ coupon.name }}</text><text class="period">{{ periodText(coupon) }}</text></view>
				<button v-if="activeTab==='available'" :loading="claimingId===coupon.templateId" :disabled="claimingId!==null||claimedIds.includes(coupon.templateId)" @tap="claim(coupon)">{{ claimedIds.includes(coupon.templateId)?'已领取':'立即领取' }}</button>
			</view>
		</view>
		<StateView v-else :title="activeTab==='available'?'暂无可领取优惠券':'暂无相关优惠券'" :description="activeTab==='available'?'新的优惠活动会在这里发布':'领取后可在这里查看和使用'" :action-text="activeTab==='available'?'查看我的券':'去领券'" @action="changeTab(activeTab==='available'?'mine':'available')" />
	</view>
</template>

<script>
	import StateView from '../../components/StateView.vue'
	import { claimCoupon, getAvailableCoupons, getMyCoupons } from '../../api/index.js'
	import { isLoggedIn } from '../../utils/auth.js'
	import { getCouponValueText, normalizeCouponList } from '../../utils/normalizers.js'
	export default{
		components:{StateView},data(){return{activeTab:'available',status:'',loading:true,error:'',available:[],mine:[],claimingId:null,claimedIds:[],statuses:[{label:'全部',value:''},{label:'未使用',value:0},{label:'已使用',value:1},{label:'已过期',value:2}]}},
		computed:{visibleCoupons(){if(this.activeTab==='available')return this.available;if(this.status==='')return this.mine;return this.mine.filter((item)=>Number(item.status)===Number(this.status))}},
		onLoad(options){if(!isLoggedIn()){uni.redirectTo({url:`/pages/auth/login?redirect=${encodeURIComponent('/pages/coupons/index')}`});return}this.activeTab=options.tab==='mine'?'mine':'available';this.status=['0','1','2'].includes(String(options.status))?Number(options.status):'';this.loadCoupons()},onPullDownRefresh(){this.loadCoupons(true)},
		methods:{valueText:getCouponValueText,amountText(value){const amount=Number(value||0);return Number.isInteger(amount)?String(amount):amount.toFixed(2)},periodText(coupon){return coupon.startTime||coupon.endTime?`${coupon.startTime||'领取后'} 至 ${coupon.endTime||'长期有效'}`:'长期有效'},async loadCoupons(fromPullDown=false){this.loading=!fromPullDown;this.error='';try{if(this.activeTab==='available'){this.available=normalizeCouponList(await getAvailableCoupons(),'available')}else{const [mineResult,templateResult]=await Promise.all([getMyCoupons(this.status===''?undefined:{status:this.status}),getAvailableCoupons()]);const templates=normalizeCouponList(templateResult,'available');this.mine=normalizeCouponList(mineResult,'mine',templates)}}catch(error){this.error=error.message||'优惠券加载失败'}finally{this.loading=false;if(fromPullDown)uni.stopPullDownRefresh()}},changeTab(tab){if(this.activeTab===tab)return;this.activeTab=tab;this.error='';this.loadCoupons()},changeStatus(value){if(this.status===value)return;this.status=value;this.loadCoupons()},async claim(coupon){if(this.claimingId!==null||this.claimedIds.includes(coupon.templateId))return;this.claimingId=coupon.templateId;try{await claimCoupon(coupon.templateId);this.claimedIds=[...this.claimedIds,coupon.templateId];uni.showToast({title:'领取成功',icon:'success'})}catch(error){uni.showToast({title:error.message||'领取失败',icon:'none'})}finally{this.claimingId=null}}},
	}
</script>

<style scoped>
	.coupon-page{min-height:100vh;padding-bottom:40rpx;background:#f5f6f8}.page-head{display:flex;padding:30rpx 28rpx 25rpx;align-items:flex-end;justify-content:space-between;background:#fff}.page-head>view text{display:block}.kicker{color:#e1251b;font-size:18rpx;font-weight:800}.title{margin-top:7rpx;color:#252a31;font-size:38rpx;font-weight:800}.page-head>text{color:#969da6;font-size:20rpx}.main-tabs{display:grid;grid-template-columns:1fr 1fr;height:82rpx;border-top:1rpx solid #f0f1f3;background:#fff}.main-tabs view{position:relative;display:flex;align-items:center;justify-content:center;color:#69717c;font-size:24rpx}.main-tabs view.active{color:#e1251b;font-weight:700}.main-tabs view.active::after{position:absolute;bottom:0;width:80rpx;height:5rpx;background:#e1251b;content:''}.status-tabs{height:76rpx;border-top:1rpx solid #eceef1;background:#fff;white-space:nowrap}.status-inner{display:flex;height:76rpx}.status-inner view{display:flex;min-width:130rpx;align-items:center;justify-content:center;color:#858d97;font-size:22rpx}.status-inner view.active{color:#e1251b}.loading{display:flex;height:60vh;align-items:center;justify-content:center;color:#969da6;font-size:24rpx}.coupon-list{padding:20rpx}.coupon-ticket{position:relative;display:grid;grid-template-columns:195rpx minmax(0,1fr) 108rpx;min-height:184rpx;margin-bottom:16rpx;overflow:hidden;border:1rpx solid #eceef1;border-radius:9rpx;background:#fff}.coupon-ticket::before,.coupon-ticket::after{position:absolute;left:183rpx;width:24rpx;height:24rpx;border-radius:50%;background:#f5f6f8;content:''}.coupon-ticket::before{top:-12rpx}.coupon-ticket::after{bottom:-12rpx}.coupon-value{display:flex;padding:24rpx 14rpx;align-items:center;justify-content:center;flex-direction:column;color:#fff;background:#e1251b;text-align:center}.coupon-value text:first-child{font-size:38rpx;font-weight:800}.coupon-value text:last-child{margin-top:10rpx;font-size:18rpx;line-height:1.4}.coupon-copy{min-width:0;padding:22rpx 17rpx}.coupon-copy>view{display:flex;align-items:center;justify-content:space-between;gap:8rpx}.coupon-copy>view text{padding:3rpx 7rpx;border-radius:4rpx;color:#e1251b;background:#fff0ee;font-size:17rpx}.coupon-name{display:block;margin-top:14rpx;overflow:hidden;color:#343a42;font-size:25rpx;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.period{display:block;margin-top:13rpx;color:#969da6;font-size:18rpx;line-height:1.4}.coupon-ticket>button{width:90rpx;height:58rpx;margin:auto 12rpx;border:1rpx solid #e1251b;border-radius:29rpx;color:#e1251b;background:#fff;font-size:20rpx;line-height:58rpx}.coupon-ticket>button[disabled]{color:#aaa;border-color:#ddd}.coupon-ticket.disabled{filter:grayscale(1);opacity:.62}.status-0{color:#58a13b!important;background:#eff8eb!important}.status-1,.status-2{color:#858d97!important;background:#f0f1f3!important}
</style>
