<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import { buyNow, createOrder, getAddressList, getMyCoupons, getProductDetail } from '../api/index.js'
import { useCartStore } from '../store/cart.js'
import { calculateCheckoutTotals, formatMoney, normalizeAddressList } from '../utils/commerce.js'
import { filterUsableCoupons, getCouponValueText, normalizeCouponList } from '../utils/coupon.js'
const route = useRoute(); const router = useRouter(); const cart = useCartStore(); const loading = ref(true); const cartUnavailable = ref(false); const addresses = ref([]); const coupons = ref([]); const addressId = ref(); const couponId = ref(); const remark = ref(''); const items = ref([])
const goodsAmount = computed(() => items.value.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.quantity || 0), 0)); const usableCoupons = computed(() => filterUsableCoupons(coupons.value, goodsAmount.value)); const selectedCoupon = computed(() => usableCoupons.value.find((item) => item.id === couponId.value)); const totals = computed(() => calculateCheckoutTotals(items.value, selectedCoupon.value))
const load = async () => { loading.value = true; try { const [addressResult, couponResult] = await Promise.all([getAddressList(), getMyCoupons({ status: 0 })]); addresses.value = normalizeAddressList(addressResult); addressId.value = addresses.value[0]?.id; coupons.value = normalizeCouponList(couponResult, 'mine').list; if (route.params.mode === 'cart') { try { await cart.fetchCartList(); items.value = cart.checkedList } catch { cartUnavailable.value = true; items.value = []; ElMessage.warning('购物车服务暂不可用，暂不能结算') } } else { const skuId = Number(route.query.skuId); const quantity = Number(route.query.quantity || 1); const detail = await getProductDetail(Number(route.query.productId || skuId)); const sku = (detail?.skuList || []).find((item) => item.id === skuId) || detail?.skuList?.[0] || {}; items.value = [{ skuId, id: skuId, quantity, name: detail?.product?.name, image: sku.image || detail?.product?.mainImage, price: Number(sku.price || 0) }] } } finally { loading.value = false } }
const submit = async () => { if (cartUnavailable.value) return ElMessage.warning('购物车服务未恢复，暂不能提交购物车订单'); if (!addressId.value) return ElMessage.warning('请先新增并选择收货地址'); if (!items.value.length) return ElMessage.warning('没有可结算商品'); const data = route.params.mode === 'cart' ? await createOrder({ cartIds: items.value.map((item) => item.id), addressId: addressId.value, couponId: couponId.value, remark: remark.value }) : await buyNow({ skuId: items.value[0].skuId, quantity: items.value[0].quantity, addressId: addressId.value, couponId: couponId.value, remark: remark.value }); const orderNo = data?.orderNo || data?.order?.orderNo || data; if (!orderNo) throw new Error('下单成功但未返回订单号'); router.replace(`/payment/${orderNo}`) }
onMounted(load)
</script>
<template><section class="commerce-page"><div class="page-title"><div><p>CHECKOUT</p><h1>确认订单</h1></div></div><el-skeleton v-if="loading" :rows="10" animated/><template v-else><el-alert v-if="route.params.mode === 'cart'" title="购物车接口异常时无法完成购物车结算；立即购买不受影响。" type="warning" :closable="false"/><h2>收货地址</h2><el-radio-group v-model="addressId" class="address-picker"><el-radio v-for="item in addresses" :key="item.id" :value="item.id" border>{{ item.receiverName }} {{ item.receiverPhone }} · {{ item.fullAddress }}</el-radio></el-radio-group><el-button link type="primary" @click="router.push('/addresses')">管理收货地址</el-button><h2>商品清单</h2><article v-for="item in items" :key="item.id" class="order-line"><img :src="item.image"><span>{{ item.name }}</span><span>× {{ item.quantity }}</span><strong>￥{{ formatMoney(item.price * item.quantity) }}</strong></article><h2>优惠券</h2><el-select v-model="couponId" clearable :placeholder="usableCoupons.length ? '请选择优惠券' : '暂无满足门槛的优惠券'"><el-option v-for="item in usableCoupons" :key="item.id" :label="`${item.name} - ${getCouponValueText(item)}`" :value="item.id"/></el-select><el-input v-model="remark" class="remark" placeholder="订单备注（选填）"/><div class="checkout-bar"><span>共 {{ totals.totalCount }} 件，优惠 ￥{{ formatMoney(totals.discountAmount) }}</span><strong>应付 ￥{{ formatMoney(totals.payableAmount) }}</strong><el-button type="primary" size="large" @click="submit">提交订单</el-button></div></template></section></template>
